# docker-compose.yml con hot reload optimizado
version: '3.8'

services:
  # Base de datos PostgreSQL
  database:
    image: postgres:15-alpine
    container_name: app_database
    restart: unless-stopped
    environment: # Aca definimos las credenciales que tiene que tener el usuario (nota/aclaracion: el usuario puede ser un admin desde pgadmin o un usuario desde el front haciendo un fetch) para que pueda hacer las operaciones necesarias (esas credenciales se las "damos mas abajo al backend")
      POSTGRES_USER: usuarioPiola 
      POSTGRES_PASSWORD: cjaifejuhu39h498e
      POSTGRES_DB: app_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuarioPiola -d app_database"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend con Express y Sequelize
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev # TODO: Cambiar a "Dockerfile"
    container_name: app_backend
    restart: unless-stopped
    environment:
      NODE_ENV: development # Esto se tiene que cambiar a production
      PORT: 3001
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: app_database 
      DB_USER: usuarioPiola # Ponemos las credenciales aca asi cuando el usuario hace una request a la base de datos tiene permisos para hacerla, sino te dice que fallo la autorizacion al usuario y no podes hacer ninguna request a la base de datos
      DB_PASSWORD: cjaifejuhu39h498e
      JWT_SECRET: your_jwt_secret_here 
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "3001:3001"
      - "9229:9229"  # Puerto para debugging
    volumes:
      - ./backend:/app # TODO: Borrarlo cuando este terminada la app
      - backend_node_modules:/app/node_modules # TODO: Borrarlo cuando este terminada la app
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network

  # Frontend con React y Hot Reload
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev # TODO: Cambiar a "Dockerfile"
    container_name: app_frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=3000
      - WDS_SOCKET_PATH=/ws
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app # TODO: Este se borra cuando terminemos la app
      - frontend_node_modules:/app/node_modules # TODO: Este se borra cuando terminemos la app
    depends_on:
      - backend
    networks:
      - app_network
    stdin_open: true
    tty: true

  # Nginx como reverse proxy (opcional)
  nginx:
    image: nginx:alpine
    container_name: app_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # TODO: Este se borra cuando terminemos la app
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

  # Redis para cache y sesiones (opcional)
  redis:
    image: redis:7-alpine
    container_name: app_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    command: redis-server --appendonly yes

  # pgAdmin 4 para administración de PostgreSQL
  pgadmin:
    build:
      context: ./pgadmin
      dockerfile: Dockerfile
    container_name: app_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'True' # Lo puse en true para ver como se veia, pero estas variables basicamente son exclusivamente para el uso del desarrollador para manejar la base de datos desde pgadmin
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin # TODO: Habria que agregar la configuracion servers.json a los volumenes en vez de dejar que pgadmin lo haga automaticamente asi podemos ponerle las credenciales personalizadas
    depends_on:
      - database
    networks:
      - app_network

volumes:
  postgres_data:
  redis_data:
  frontend_node_modules: # TODO: Este se borra cuando terminemos la app
  backend_node_modules: # TODO: Este se borra cuando terminemos la app
  pgadmin_data:

networks:
  app_network:
    driver: bridge
